Validate the status of the etcd snapshot during backup and restore
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

diff --git a/bindata/etcd/etcd-common-tools b/bindata/etcd/etcd-common-tools
--- a/bindata/etcd/etcd-common-tools
+++ b/bindata/etcd/etcd-common-tools
@@ -31,3 +31,11 @@ function exec_etcdctl {
   fi
   crictl exec -it $container_id /bin/sh -c "etcdctl $command"
 }
+
+function check_snapshot_status() {
+  local snap_file="$1"
+  if ! etcdctl snapshot status "${snap_file}" -w json; then
+    echo "Backup integrity verification failed. Backup appears corrupted. Aborting!"
+    return 1
+  fi
+}
