stop referencing DNS in env vars

diff --git a/bindata/etcd/openshift-recovery-tools b/bindata/etcd/openshift-recovery-tools
--- a/bindata/etcd/openshift-recovery-tools
+++ b/bindata/etcd/openshift-recovery-tools
@@ -273,7 +273,7 @@ etcd_member_add() {
     rm -rf $ETCD_DATA_DIR
   fi
 
-  RESPONSE=$($ETCDCTL_WITH_TLS --endpoints ${RECOVERY_SERVER_IP}:2379 member add $ETCD_NAME --peer-urls=https://${ETCD_DNS_NAME}:2380)
+  RESPONSE=$($ETCDCTL_WITH_TLS --endpoints ${RECOVERY_SERVER_IP}:2379 member add $ETCD_NAME --peer-urls=https://${ETCD_URL_HOST}:2380)
   if [ $? -eq 0 ]; then
     echo "$RESPONSE"
     APPEND_CONF=$(echo "$RESPONSE" | sed -e '1,2d')
@@ -449,7 +449,7 @@ validate_environment() {
         [ ! -d $(dirname "${RUN_ENV}") ] && mkdir -p $(dirname "${RUN_ENV}")
         cat > $RUN_ENV << EOF
 ETCD_IPV4_ADDRESS=$DIG_IP
-ETCD_DNS_NAME=$a
+ETCD_URL_HOST=$a
 ETCD_WILDCARD_DNS_NAME=*.${DISCOVERY_DOMAIN}
 EOF
         return 0
@@ -460,11 +460,11 @@ EOF
   exit 1
 }
 
-# validate_etcd_name uses regex to return the etcd member name key from ETCD_INITIAL_CLUSTER matching the local ETCD_DNS_NAME.
+# validate_etcd_name uses regex to return the etcd member name key from ETCD_INITIAL_CLUSTER matching the local ETCD_URL_HOST.
 validate_etcd_name() {
-  ETCD_NAME=$(echo ${ETCD_INITIAL_CLUSTER} | grep -oP "(?<=)[^,,\s]*(?==[^=]*${ETCD_DNS_NAME}\b)") || true
+  ETCD_NAME=$(echo ${ETCD_INITIAL_CLUSTER} | grep -oP "(?<=)[^,,\s]*(?==[^=]*${ETCD_URL_HOST}\b)") || true
   if [ -z "$ETCD_NAME" ]; then
-    echo "Validating INITIAL_CLUSTER failed: ${ETCD_DNS_NAME} is not found in ${ETCD_INITIAL_CLUSTER}" >&2
+    echo "Validating INITIAL_CLUSTER failed: ${ETCD_URL_HOST} is not found in ${ETCD_INITIAL_CLUSTER}" >&2
     exit 1
   fi
   echo "$ETCD_NAME"
